### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/windows-installer#30]
@ACharbonneau mention at July 07th debriefing session that the SQLite provided by Anaconda have some problem and one workaround is changing the PATH so that the "native" SQLite is used. @mckays630 confirmed the problem.

**Comment by ethanwhite** [comment]
Just to make sure we understand:

1. Anaconda distributes a version of `sqlite3` and so does our Windows installer
2. Students install Anaconda to be the default Python, which puts the `anaconda/bin` directory at the beginning of the PATH
3. There is something not quite right about the Anaconda version of `sqlite3` (this should get reported to them)
4. We should change the PATH in such a way as to load the version that we are distributing

**Comment by ACharbonneau** [comment]
Mostly accurate. The only changes are:

 It's not just a Windows problem. I only installed Anaconda the day of the
workshop so I could follow along with the other instructor, and then found
that it broke my Macs native sqlite3. Installing Anaconda as per the
current instructions just makes it the default sqlite3. We ended up having
to fix the PATH of everyone in the class that had recently installed
Anaconda, regardless of OS.

Its already an issue on the Anaconda Github repo
https://github.com/ContinuumIO/anaconda-issues/issues/307. The only way I
figured out the problem was the magic of Google :)

4. We should change the PATH in such a way as to load the native sqlite3 or
the version we are distributing

-Amanda

**Comment by wking** [comment]
On Wed, Jul 08, 2015 at 02:28:08PM -0700, Amanda Charbonneau wrote:
> It's not just a Windows problem. I only installed Anaconda the day
> of the workshop so I could follow along with the other instructor,
> and then found that it broke my Macs native sqlite3.

It's hard to fix this just by changing the PATH.  We can shift the
Anaconda-specific component to the end of the PATH in the
.bash_profile we install on Windows, but that puts folks at risk of
*not* clobbering a system ‘conda’.  The real solution is addressing
ContinuumIO/anaconda-issues#372 (and that would help folks on
non-Windows OSes too).

In any event, I think readline for SQLite is a small enough problem
that it's not worth creating OS X or Linux SWC installers.  Is there
enough other material that such installers would be useful?  Or is
this something that's better addressed by a note in the OS X / Linux
setup instructions?

**Comment by ethanwhite** [comment]
Thanks for the clarification @ACharbonneau. Since this is a multi-OS issue I agree with @wking that we're probably better off seeing if https://github.com/ContinuumIO/anaconda-issues/issues/372 or something equivalent goes through than trying to patch this right away on just one OS. Trying to fix this in the Windows Installer would probably also introduce some order of installation dependencies which wouldn't be ideal.

**Comment by r-gaia-cs** [comment]
@wking and @ethanwhite What about https://github.com/swcarpentry/workshop-template/pull/230 until https://github.com/ContinuumIO/anaconda-issues/issues/307 isn't fixed?

**Comment by ethanwhite** [comment]
It's better than nothing for the moment.

Fixing path issues across 3 operating systems for lots of students is never much fun. But, to fix the bigger problem we do need a cross-OS solution and if there are any Windows related hiccups with that solution then we can clean those up in the Windows Installer.

**Comment by rgaiacs** [comment]
@ethanwhite @wking Can we close this?

**Comment by ethanwhite** [comment]
@rgaiacs - I'm no longer maintaining the Windows Installer, so that's up to @wking and @embray now.
